### ISSUE TITLE
Single GPU passthrough support

### ISSUE THREAD

**Issue by Ironfist69** [uwzis/GPU-Passthrough-Manager#24]
Need Single GPU passthrough support 🙂

**Comment by uwzis** [comment]
Single GPU passthrough is passing a single GPU to a virtual machine by loading vfio drivers to your PCI device. It is basically to my knowledge impossible to passthrough your only GPU to a virtual machine because your host system needs the GPU to boot. If you passthrough your only GPU it will fail loading the driver in my testing. "Single GPU passthrough" in your context does not exist. But you can do GPU partitioning and give your VM a percentage of your GPU. This is the only way you can get away with one GPU in your system.

**Comment by uwzis** [comment]
I will be adding support soon for GPU partitioning in the next release. Thank you for feedback!

**Comment by gardotd426** [comment]
I was going to open this same issue as a feature request, but I checked to make sure it wasn't already requested and found this. @uwzis you are mistaken on some things. 

>Single GPU passthrough is passing a single GPU to a virtual machine by loading vfio drivers to your PCI device. It is basically to my knowledge impossible to passthrough your only GPU to a virtual machine because your host system needs the GPU to boot. If you passthrough your only GPU it will fail loading the driver in my testing. "Single GPU passthrough" in your context does not exist

Single GPU passthrough 100% **does** exist, and there are countless guides on the internet, but no automation software. I had a single GPU passthrough setup for a year and a half, but I deleted it and was wanting to re-set it up but didn't feel like spending the 2 days it took last time setting it up. 

What happens is you dynamically unload the driver with libvirt hooks, using a script most people call `start.sh` (in `/etc/libvirt/hooks/qemu.d/<VMNAME>/prepare/begin/`). Your GPU is detached using envars in `/etc/libvirt/hooks/kvm.conf` (also where you set up your memory allocation and stuff), and your screens flash and the VM boots up and now controls your whole GPU. When you shut the VM down, the script `/etc/libvirt/hooks/qemu.d/win10/release/end/revert.sh` activates and unbinds the vfio drivers and re-binds the Nvidia (or AMD I guess) drivers (also, allocating and de-allocating hugepages goes in those directories as a script if you want one). You are brought back to the log-in screen, simple as that. 

It is no different from single-GPU passthrough, only you can't use both **GUIs** at the same time, I regularly had a powershell prompt up where I was ssh-ed into the host and ran my `gotop` and `nmon` and other processes on my second monitor because I trust them more than Windows and I'm more used to them. 

Here is a video that illustrates how it functions from the user's point of view, where you see me click Start on the VM, my screens flash, the VM boot logo shows, and Windows pops up. I kill the VM, and I'm back at the SDDM login. 

https://youtu.be/NIIt462OW-g

It'd be cool if you could re-open this issue if you're considering it (since you now know it is, in fact, a thing), or if you're not interested in implementing/supporting it, if you could say as much so we're not wondering. 

Some of the major guides used, that thoroughly explain it:

https://github.com/joeknock90/Single-GPU-Passthrough

https://gitlab.com/risingprismtv/single-gpu-passthrough

https://gitlab.com/Karuri/vfio (this is the one I used the most back when I set it up).
