### ISSUE TITLE
[Question] - How to use with optimus-manager

### ISSUE THREAD

**Issue by Jorman** [uwzis/GPU-Passthrough-Manager#35]
Hi, I'm pretty new to this topic, so I'm trying to better understand all, with a lot of test.

I've one laptop with Arch installed and with two graphics card
```
lspci | grep -E 'VGA|Display|3D'
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] (rev a1)
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c6)
```

I installed GPU-Passthrough-Manager and all ok, I can isolate the nVidia resources and till here all ok, I think I'm still testing all the system.
So if I isolate the nVidia devices I can't use it inside Arch, am I right?
Actually if I make some test without drivers isolation I can do `prime-run ./program` to start the `program` with nVidia card or directly start the `program` and in this case the `program` run with AMD card
Then I installed `optimus-manager` I set the `Hybrid mode` at boot and all is still working, like nothing has changed, so I don't know if I'm on the right way.
Then, after all, I run GPU-Passthrough-Manager, isolate the nVidia driver but after reboot I can't run program with `prime-run` command.
Maybe is normal or maybe I'm doing it in the wrong way?
Is possible to "isolate" the nVidia devices for VM and at the same time use if needed under linux? Obviously or under VM or under Linux

**Comment by uwzis** [comment]
I use Optimus Manager with a ROG gaming laptop from 2020 with a 2060 mobile. I use Optimus Manager to throw my GPU off of the pci bus to save battery life and IT HELPS SIGNIFICANTLY.  I double my battery life but since you run AMD, you will get almost 3 times. If you kick it off the bus like I do it cant be used so it doesn't take 5W of idle power draw, but if you want to use the gpu normally, then just switch to the GPU through Optimus Manager, but If you are trying to run a windows VM using something like looking glass or an external monitor, then just switch to Hybrid or NVIDIA. This will cause Optimus Manager to try to use the NVIDIA GPU but it cant because the vfio driver has been loaded. This will break out of Optimus Manager and if you have Optimus Manager qt installed, you should no longer see the tray icon on your screen. Then all you have to do is pass it through to a VM and you can get graphics from an external monitor to set up looking glass. You can just load default drivers on the system to go back to normal. NOTE that all Nvidia MAX-Q cards may not work on VMs because NVIDIA blocked it in firmware. I saw a fix on archlinux.org but I haven't had to do it so your mileage may vary.

**Comment by Jorman** [comment]
Hi,
my board is not a MAX-Q, fortunately, so I don't need the patch either.
I currently have these options in Optimus-Manager:
![immagine](https://user-images.githubusercontent.com/5203988/214949680-6b5a779c-825c-4624-9e1c-70ca6dbc426e.png)
I don't use a second monitor, I would just like to use the nVidia card in the virtual machine, when it is obviously on, in order to take advantage of the GPU. When the virtual machine is off, however, I would like to use the nVidia card in Arch, either via prime-run or via Optimus-Manager, when I need it, assuming it is possible to use the latter. 

I'm still not clear on the functionality of Optimus-Manager side-by-side with isolating the nVidia drivers by loading the vfio module in the kernel, so let's see if I understand how it works:
1. If Optimus-Manager is running in integrated mode, the main driver is Amd's APU driver, so I can isolate the nVidia card with your program and vfio drivers. This way the virtual machine can use the nVidia card. In this scenario, the nVidia is always working and comsume power
2.  If, on the other hand, I use the nVidia card in Optimus-Manager, I can no longer isolate any peripheral as it is in use and I cannot use the virtual machine with the nVidia card
3.  If Optimus-Manager is in hybrid mode, I didn't understand what I can do. It's as you say, the Optimus-Manager program is no longer visible, but it doesn't seem to me that I can use the nVidia card in and out of virtual machine, obviously either one or the other.

I don't want to use looking glass, I would like to be able to best configure VMM7

What advantages does the Hybrid mode of Optimus-Manager bring?
Can I for example load vfio and at the same time use prime-run when needed?

I still need to do some testing to get a good understanding of how it works first, but as you can see the Hybrid mode is confusing me, also because I have never experimented in this area

Do you have any advice as well as maybe some information that resolves these doubts?

Jorman

**Comment by uwzis** [comment]
I don't use hybrid but I am pretty sure it just uses the NVIDIA GPU under heavy workloads instead of the IGPU. You can go in settings and figure out all of the features that come with it. If you aren't kicking the card off the bus it will just work regardless because it is on the bus.
