### ISSUE TITLE
screwed up my grub.cfg

### ISSUE THREAD

**Issue by TheOncomingStorm** [uwzis/GPU-Passthrough-Manager#37]
I'm not having any other issues with this but it did screw up my grub.cfg so badly that I had to recover from a backup. I might suggest having the program make a backup to prevent major issues with people who don't have backups, especially since my backup wasn't recent. That said, I did swap in the new linux command line and it seems to work fine.

**Comment by ajgringo619** [comment]
The file you need to backup/restore would be `/etc/default/grub`, not `/boot/grub/grub.cfg`. All it added to mine was "rd.driver.pre=vfio-pci" in `GRUB_CMDLINE_LINUX_DEFAULT=`

Agree wholeheartedly that it should make a backup first.

**Comment by uwzis** [comment]
The first time setup script adds intel_iommu=on or amd_iommu=on depending on what CPU your system has. This one parameter shouldn't mess up your system unless your system doesn't support iommu or your grub config was screwed up before that. I have also had a grub problem with my system when I updated and made the config it would break regardless. This is not a program issue, this is a grub issue. I would make an issue on grub on iommu being enabled screws up the config because this script just uses sed to add the parameter to the grub config.

**Comment by ajgringo619** [comment]
Thanks for the clarification; already had 'amd_iommu=on'.

**Comment by TheOncomingStorm** [comment]
Those parameters didn't affect me. As I mentioned before, I already added them into the current grub.cfg and they're not causing problems. Nor was my grub bad because I just rebuilt it manually with no problems. I truly have no clue what may have caused it but the only time I've experienced something similar is when a typo is introduced(by me usually) to grub.cfg. I did use the AUR version of this so I'll see if they do any patches or the like but otherwise I'm clueless what else could cause it. I've checked grub.cfg(and /etc/default/grub) and can't find the problem so I'm suspecting it's an invisible control character or the like but nothing stands out.  WEIRD. 

For the record, my grub.cfg being bad meant I couldn't boot at all until I swapped in a good one. Once I did it worked fine, even with the additional parameters.

**Comment by ajgringo619** [comment]
I try not to ever edit grub.cfg directly. I use the files in `/etc/grub.d`, so if one is bad, I can just remove the executable permissions and update grub again.

**Comment by uwzis** [comment]
In conclusion, Grub is just a boot loader that isn't that reliable. On my machine I had to get pacman to ignore it because if I updated it it just broke. I would try an older version of grub if you can. The First time setup script will ignore updating the grub config if it finds iommu already enabled and the same for mkinitcpio, initramfs, dracut... So if you do it manually before you download GPUPM then run it, It will do nothing. You can check this by running it via the terminal and it will tell you what it adds to the configs or what is found in them.
